env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - react-app
  - react-app/jest
  - typescript
  - typescript/react

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

ignorePatterns:
  - build

settings:
  react:
    version: detect

rules: {}
