root: true

env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - prettier
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'
  - jsx-a11y
  - react-hooks

ignorePatterns:
  - build
  - dist

settings:
  react:
    version: detect

rules:
  react/jsx-uses-vars: warn
  react/jsx-uses-react: warn

overrides:
  - files: ['*.config.ts', '*.config.js']
    env:
      node: true
