env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - prettier
  - react-app
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'

ignorePatterns:
  - build
  - dist

settings:
  react:
    version: detect

rules: {}

overrides:
  - files: ['*.config.ts', '*.config.js']
    env:
      node: true
