env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - react-app
  - react-app/jest
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'

ignorePatterns:
  - build

settings:
  react:
    version: detect

rules: {}
